p8105_hw2_ys3766
================
Yifan Shi
2024-10-02

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

### Problem 1

Importing data, cleaning data, selecting variables

``` r
transit = 
  read_csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11= "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, entry, exit_only, vending, entrance_type, ada,
    starts_with("route")
  ) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

The resulting data set contains 1868 observations of 20 variables now.
It has variables on NYC subway lines, stations, location of the station,
entry and exit information, vending, ADA compliance information and
routes.I cleaned the data by converting column types of route8-route11,
cleaning the names of the variables, selecting relevant variables, and
converting the entry variable to logical. I would say the dataset is not
yet tidy, as the route variables is currently wide format. To further
tidy the data set, I would convert the route variables from wide to long
format, and create a new “route number” variable.

Number of distinct stations

``` r
transit %>% 
 distinct(line, station_name) %>% 
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

ADA compliant stations

``` r
transit %>% 
  filter(ada == TRUE) %>% 
  distinct(line, station_name) %>% 
  nrow()
```

    ## [1] 84

There are 84 ADA compliant stations.

Proportion of station entrances/exits without vending allow entrance

``` r
transit %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean()
```

    ## [1] 0.3770492

37.7% of station entrances/exits without vending allow entrance

Reformat the data so that route number and route name are distinct
variables

``` r
transit<-transit %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route"
  )
```

Distinct stations serve the A train, how many ADA compliant

``` r
transit %>% 
  filter(route == "A") %>% 
  distinct(line, station_name) %>% 
  nrow()
```

    ## [1] 60

``` r
transit %>% 
  filter(route == "A", ada == TRUE) %>% 
  distinct(line, station_name) %>% 
  nrow()
```

    ## [1] 17

There are 60 distinct stations serving the A train, of which 17 are ADA
compliant.

### Problem 2

import and tidy the sheet Mr Trash Wheel

``` r
mr_trash_wheel = 
  read_excel('data/202409 Trash Wheel Collection Data.xlsx', 
             sheet = 'Mr. Trash Wheel',
             range = cell_cols("A:N"),
             skip = 1,
             ) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(sports_balls = as.integer(round(sports_balls)),
         year = as.numeric(year))
```

import and tidy the sheet Professor Trash Wheel

``` r
prof_trash_wheel = 
  read_excel('data/202409 Trash Wheel Collection Data.xlsx', 
             sheet = 'Professor Trash Wheel',
             range = cell_cols("A:M"),
             skip = 1,
             ) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster))
```

import and tidy the sheet Gwynnda Trash Wheel

``` r
gwynnda_trash_wheel = 
  read_excel('data/202409 Trash Wheel Collection Data.xlsx', 
             sheet = 'Gwynnda Trash Wheel',
             range = cell_cols("A:L"),
             skip = 1,
             ) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) 
```

Create an indicator variable for the sourse, then combine the 3
individual df to produce a single df

``` r
mr_trash_wheel<- mr_trash_wheel %>% 
  mutate(source = "Mr. Trash Wheel")

prof_trash_wheel<- prof_trash_wheel %>% 
  mutate(source = "Professor Trash Wheel")

gwynnda_trash_wheel <- gwynnda_trash_wheel %>% 
  mutate(source = "Gwynnda Trash Wheel")

trash_wheel <- bind_rows(mr_trash_wheel, prof_trash_wheel, gwynnda_trash_wheel) %>% 
  relocate(source)
```

Total weight of trash collected by professor trash wheel

``` r
trash_wheel %>% 
  filter(source == "Professor Trash Wheel") %>% 
  summarise(total_weight = sum(weight_tons, na.rm = TRUE)) %>% 
  pull(total_weight)
```

    ## [1] 246.74

Total nuber of cigarette butts collected by Gwynnda in june 2022

``` r
trash_wheel %>% 
  filter(source == "Gwynnda Trash Wheel", month == "June", year == 2022) %>% 
  summarise(total_cig = sum(cigarette_butts, na.rm = TRUE)) %>% 
  pull(total_cig)
```

    ## [1] 18120

The combined dataset consists of 1033 observations of 15 variables,
spanning multiple years and encompassing data from the 3 trash wheels,
namely the Mr. Trash Wheel, Professor Trash Wheel, and Gwynnd Trash
Wheel. It has variables on dumpter number, date of collection, amount of
total litter and litter type.

The total weight of trash collected by Professor Trash Wheel was 246.74
tons. The total number of cigarette butts collected by Gwynnda in June
of 2022 was 18120.
